[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = ["futures/std"]
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = { version = "0.1.3", optional = true }
log = { version = "0.4.11", optional = true }

cortex-m = "0.7.1"
futures     = { version = "0.3.5", default-features = false, features = [ "cfg-target-has-atomic", "unstable" ] }
pin-project = { version = "1.0.2", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
atomic-emu  = { version = "0.1.0", path = "../atomic-emu"}

